title:              Data portfolio
email:              elarralde@gmail.com
description:        Data gathering, wrangling, EDA and visualization projects
author:             Estitxu Larralde Erasun
baseurl:            ""
url:                "https://pitxunet.github.io"

# Social Profiles
twitter_username:   EstitxuLE
github_username:    Pitxunet
facebook_username:  Estitxu Larralde Erasun
instagram_username:  
linkedin_username:  estitxu-larralde-erasun

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
